### ISSUE TITLE
Installation: cookiecutter.exceptions.NonTemplatedInputDirException

### ISSUE THREAD

**Issue by will-Do** [talperetz/scalable-airflow-template#1]
Hi,
I'm trying to deploy airflow by this template, but got no luck :(
It there sth I missed?

`
Select airflow_executor:
1 - Kubernetes
2 - Celery
Choose from 1, 2 [1]:
local_airflow_image_name [xxxxx/airflow]:
airflow_image_repository [puckel/docker-airflow]:
git_repo_to_sync_dags [https://github.com/xxxxxx/flows.git]:
git_username_in_base_64 [2NTTi6bOy]:
git_password_in_base_64 [laTQudhlZe2NTTi6bOyV]:
fernet_key [vOAtprdE8VMtyKUik63i8QQm16a0Gm76-D4nj5qQAwI=]:
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    load_entry_point('cookiecutter==1.6.0', 'console_scripts', 'cookiecutter')()
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/cookiecutter/generate.py", line 257, in generate_files
    template_dir = find_template(repo_dir)
  File "/usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages/cookiecutter/find.py", line 36, in find_template
    raise NonTemplatedInputDirException
cookiecutter.exceptions.NonTemplatedInputDirException
`

find.py:
```
      for item in repo_dir_contents:
      ¦   if 'cookiecutter' in item and '{{' in item and '}}' in item:
      ¦   ¦   project_template = item
      ¦   ¦   break

      if project_template:
      ¦   project_template = os.path.join(repo_dir, project_template)
      ¦   logger.debug(
      ¦   ¦   'The project template appears to be {}'.format(project_template)
      ¦   )
      ¦   return project_template
      else:
      ¦   raise NonTemplatedInputDirException
```

**Comment by eAmine** [comment]
This is still not working out of the box for me :(
